// Shared browser JSON implementation; consumer copies are generated by build-browser.py.
export const SEAL_PROFILE = "allowly.seal.jcs-sha256.v1";
export const MAX_SEAL_JSON_BYTES = 1024 * 1024;
export const MAX_SEAL_JSON_DEPTH = 32;

export class SealJsonError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SealJsonError";
  }
}

function hasUnpairedSurrogate(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) return true;
      index += 1;
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      return true;
    }
  }
  return false;
}

function normalizedDecimal(token: string): { negative: boolean; digits: string; exponent: bigint } {
  const match = /^(-)?(0|[1-9]\d*)(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/.exec(token);
  if (!match) throw new SealJsonError("JSON contains an invalid number.");
  const fraction = match[3] ?? "";
  const exponentText = (match[4] ?? "0").replace(/^[+-]?0+(?=\d)/, (zeros) => zeros.startsWith("-") ? "-" : "");
  let digits = `${match[2]}${fraction}`.replace(/^0+/, "");
  if (!digits) return { negative: false, digits: "0", exponent: 0n };
  if (exponentText.replace(/^[+-]/, "").length > 6) {
    throw new SealJsonError("JSON contains a number outside the supported IEEE-754 range.");
  }
  let exponent = BigInt(exponentText) - BigInt(fraction.length);
  while (digits.endsWith("0")) {
    digits = digits.slice(0, -1);
    exponent += 1n;
  }
  return { negative: Boolean(match[1]), digits, exponent };
}

function sameDecimalValue(left: string, right: string): boolean {
  const a = normalizedDecimal(left);
  const b = normalizedDecimal(right);
  return a.negative === b.negative && a.digits === b.digits && a.exponent === b.exponent;
}

export function parseStrictJson(text: string): unknown {
  if (typeof text !== "string") throw new SealJsonError("Record JSON must be text.");
  if (new TextEncoder().encode(text).length > MAX_SEAL_JSON_BYTES) {
    throw new SealJsonError("Record JSON must be 1 MiB or smaller.");
  }

  let index = 0;
  const numberPattern = /-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/y;

  function fail(message: string): never {
    throw new SealJsonError(`${message} (character ${index + 1}).`);
  }

  function skipWhitespace() {
    while (index < text.length && /[\t\n\r ]/.test(text[index])) index += 1;
  }

  function parseString(): string {
    const start = index;
    index += 1;
    while (index < text.length) {
      const code = text.charCodeAt(index);
      if (text[index] === '"') {
        index += 1;
        let value: string;
        try {
          value = JSON.parse(text.slice(start, index)) as string;
        } catch {
          fail("JSON contains an invalid string");
        }
        if (hasUnpairedSurrogate(value)) fail("JSON strings cannot contain unpaired Unicode surrogates");
        return value;
      }
      if (code < 0x20) fail("JSON strings cannot contain unescaped control characters");
      if (text[index] === "\\") {
        index += 1;
        if (index >= text.length) fail("JSON contains an unfinished string escape");
        const escape = text[index];
        if (escape === "u") {
          const hex = text.slice(index + 1, index + 5);
          if (!/^[0-9a-fA-F]{4}$/.test(hex)) fail("JSON contains an invalid Unicode escape");
          index += 5;
          continue;
        }
        if (!'"\\/bfnrt'.includes(escape)) fail("JSON contains an invalid string escape");
      }
      index += 1;
    }
    fail("JSON contains an unfinished string");
  }

  function parseNumber(): number {
    numberPattern.lastIndex = index;
    const match = numberPattern.exec(text);
    if (!match) fail("JSON contains an invalid number");
    const token = match[0];
    index = numberPattern.lastIndex;
    const value = Number(token);
    if (!Number.isFinite(value)) fail("JSON numbers must be finite IEEE-754 values");
    if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
      fail("JSON integers must stay within the IEEE-754 safe integer range");
    }
    const canonical = JSON.stringify(value);
    if (!sameDecimalValue(token, canonical)) {
      fail("JSON contains a number that would lose precision in this browser");
    }
    return value;
  }

  function parseArray(depth: number): unknown[] {
    index += 1;
    skipWhitespace();
    const result: unknown[] = [];
    if (text[index] === "]") {
      index += 1;
      return result;
    }
    while (true) {
      result.push(parseValue(depth + 1));
      skipWhitespace();
      if (text[index] === "]") {
        index += 1;
        return result;
      }
      if (text[index] !== ",") fail("Expected ',' or ']' in array");
      index += 1;
      skipWhitespace();
    }
  }

  function parseObject(depth: number): Record<string, unknown> {
    index += 1;
    skipWhitespace();
    const result: Record<string, unknown> = Object.create(null) as Record<string, unknown>;
    const keys = new Set<string>();
    if (text[index] === "}") {
      index += 1;
      return result;
    }
    while (true) {
      if (text[index] !== '"') fail("Object keys must be JSON strings");
      const key = parseString();
      if (keys.has(key)) fail(`Duplicate object key ${JSON.stringify(key)} is not allowed`);
      keys.add(key);
      skipWhitespace();
      if (text[index] !== ":") fail("Expected ':' after object key");
      index += 1;
      result[key] = parseValue(depth + 1);
      skipWhitespace();
      if (text[index] === "}") {
        index += 1;
        return result;
      }
      if (text[index] !== ",") fail("Expected ',' or '}' in object");
      index += 1;
      skipWhitespace();
    }
  }

  function parseValue(depth: number): unknown {
    if (depth >= MAX_SEAL_JSON_DEPTH) {
      throw new SealJsonError(`Record JSON nesting cannot exceed ${MAX_SEAL_JSON_DEPTH} levels.`);
    }
    skipWhitespace();
    const char = text[index];
    if (char === '"') return parseString();
    if (char === "{") return parseObject(depth);
    if (char === "[") return parseArray(depth);
    if (char === "-" || (char >= "0" && char <= "9")) return parseNumber();
    for (const [literal, value] of [["true", true], ["false", false], ["null", null]] as const) {
      if (text.startsWith(literal, index)) {
        index += literal.length;
        return value;
      }
    }
    fail("Expected a JSON value");
  }

  skipWhitespace();
  if (index === text.length) throw new SealJsonError("Record JSON is empty.");
  const value = parseValue(0);
  skipWhitespace();
  if (index !== text.length) fail("JSON has unexpected trailing content");
  return value;
}

export function canonicalizeJson(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new SealJsonError("JSON numbers must be finite.");
    return JSON.stringify(value);
  }
  if (typeof value === "string") {
    if (hasUnpairedSurrogate(value)) throw new SealJsonError("JSON strings cannot contain unpaired Unicode surrogates.");
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) return `[${value.map(canonicalizeJson).join(",")}]`;
  if (typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
      .map(([key, item]) => `${JSON.stringify(key)}:${canonicalizeJson(item)}`)
      .join(",")}}`;
  }
  throw new SealJsonError(`Unsupported JSON value: ${typeof value}.`);
}

export async function fingerprintJson(text: string): Promise<{ canonical: string; recordSha256: string }> {
  const canonical = canonicalizeJson(parseStrictJson(text));
  const canonicalBytes = new TextEncoder().encode(canonical);
  if (canonicalBytes.length > MAX_SEAL_JSON_BYTES) {
    throw new SealJsonError("Canonical record JSON must be 1 MiB or smaller.");
  }
  const digest = await crypto.subtle.digest("SHA-256", canonicalBytes);
  const recordSha256 = Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
  return { canonical, recordSha256 };
}
